---
# Homepage configuration
# See https://fontawesome.com/v5/search for icons options

title: "Moogi - Homer"
subtitle: "If you don't control the software, it controls you."
logo: "logo.png"
# icon: "fas fa-skull-crossbones" # Optional icon

header: true
footer: '<p style="color:white">Created with <span class="has-text-danger">❤️</span> by Moogi and Defalco64</p>' # set false if you want to hide it.

# Optional theme customization
theme: walkxcode

columns: "3"

defaults:
  layout: columns

# Optional message
# message:
#   style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
#   title: "👋 Welcome!"
#   content: "Welcome to Moogi! Enjoy our self-hosted services. :)"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
# links:
#   - name: "Contribute!"
#     icon: "fab fa-github"
#     url: "https://github.com/bastienwirtz/homer"
#     target: "_blank" # optional html a tag target attribute
#   - name: "Documentation"
#     icon: "fas fa-book"
#     url: "https://github.com/bastienwirtz/homer/blob/main/README.md#table-of-contents"
#   # this will link to a second homer page that will load config from additional-page.yml and keep default config values as in config.yml file
#   # see url field and assets/additional-page.yml.dist used in this example:
#   - name: "another page!"
#     icon: "fas fa-file-alt"
#     url: "#additional-page" 

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Services"
    icon: "fas fa-layer-group"
    items:
      - name: "Bitwarden"
        logo: "https://i.imgur.com/Jof7XKk.png"
        url: "https://vault.moogi.tech"
      - name: "Gitea"
        logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Gitea_Logo.svg/1200px-Gitea_Logo.svg.png"
        url: "https://git.moogi.tech"
      - name: "Affine"
        logo: "https://i.imgur.com/Drt3I3q.jpeg"
        url: "https://affine.moogi.tech"
      - name: "OpenBooks"
        logo: "https://cdn-icons-png.flaticon.com/512/5328/5328095.png"
        url: "https://books.moogi.tech"
      - name: "PasteBin"
        logo: "https://upload.wikimedia.org/wikipedia/en/3/35/Pastebin.com_logo.png"
        url: "https://bin.moogi.tech"
  - name: "Media"
    icon: "fas fa-photo-video"
    items: 
      - name: "SudoFlix"
        logo: "https://i.imgur.com/4YXAWqh.png"
        url: "https://cinema.moogi.tech"
      - name: "MeTube"
        logo: "https://i.imgur.com/jHRB2iQ.png"
        url: "https://ytdl.moogi.tech"
      - name: "Mango"
        logo: "https://avatars.githubusercontent.com/u/78470664"
        url: "https://manga.moogi.tech"
  - name: "Networking"
    icon: "fa-solid fa-server"
    items:
      - name: "Pi-Hole"
        logo: "https://upload.wikimedia.org/wikipedia/en/1/15/Pi-hole_vector_logo.svg"
        url: "https://pihole.moogi.tech"
      - name: "VPN"
        logo: "https://i.imgur.com/mELrQIC.png"
        url: "https://vpn.moogi.tech"
